// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package products

import (
	"database/sql"
)

type ApplicantProfile struct {
	UserID         int32
	FirstName      sql.NullString
	LastName       sql.NullString
	ResumeFilename sql.NullString
	School         sql.NullString
	College        sql.NullString
	Age            sql.NullInt32
}

type ApplicantSkill struct {
	SkillID int32
	UserID  int32
}

type JobPosting struct {
	PostingID   int32
	CompanyName string
}

type RecruiterProfile struct {
	UserID             int32
	CompanyName        sql.NullString
	CompanyDescription sql.NullString
}

type RoleMaster struct {
	ID   int32
	Name sql.NullString
}

type Skill struct {
	SkillID int32
	Name    sql.NullString
}

type SkillsReq struct {
	SkillID   int32
	PostingID int32
}

type User struct {
	UserID       int32
	Email        string
	Username     string
	PasswordHash sql.NullString
	RoleID       sql.NullInt32
	CreatedAt    sql.NullTime
}
