// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package products

import (
	"database/sql"
)

type ApplicantProfile struct {
	UserID         int32
	FirstName      sql.NullString
	LastName       sql.NullString
	ResumeFilename sql.NullString
	School         sql.NullString
	College        sql.NullString
	Age            sql.NullInt32
}

type ApplicantSkill struct {
	SkillID int32
	UserID  int32
}

type Interview struct {
	PostingID         int32
	UserID            int32
	InterviewDatetime sql.NullTime
	Accepted          bool
	DeclinedComplete  bool
	AnotherdateReq    bool
	AnotherDatetime   sql.NullTime
}

type JobPosting struct {
	PostingID      int32
	UserID         sql.NullInt32
	JobTitle       sql.NullString
	JobDescription sql.NullString
	PostingDate    sql.NullTime
}

type JobpostingApplicant struct {
	PostingID int32
	UserID    int32
}

type RecruiterProfile struct {
	UserID             int32
	CompanyName        sql.NullString
	CompanyDescription sql.NullString
	Approved           bool
	DeclinedCompletely bool
}

type RoleMaster struct {
	ID   int32
	Name sql.NullString
}

type Skill struct {
	SkillID int32
	Name    sql.NullString
}

type SkillsReq struct {
	SkillID   int32
	PostingID int32
}

type User struct {
	UserID       int32
	Email        string
	Username     string
	PasswordHash sql.NullString
	RoleID       sql.NullInt32
	CreatedAt    sql.NullTime
}
