// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package products

import (
	"database/sql"
)

type ApplicantProfile struct {
	UserID     int32
	FirstName  sql.NullString
	LastName   sql.NullString
	SkillID    sql.NullInt32
	ResumeName sql.NullString
	ResumeData []byte
}

type RecruiterProfile struct {
	UserID      int32
	CompanyName string
}

type RoleMaster struct {
	ID   int32
	Name sql.NullString
}

type Skill struct {
	SkillID int32
	Name    sql.NullString
}

type User struct {
	UserID       int32
	Username     string
	PasswordHash string
	RoleID       sql.NullInt32
}
